#!/bin/sh

main() {
  printf "Enter game folder name: "
  read -r folder
  path=~/dos/c/games/"$folder"
  echo "$path"
  mkdir -p "$path"

  {
    echo "*"
    echo "!.gitignore"
    echo "!run.bat"
  } >"$path/.gitignore"

  # echo "runner $folder.exe \"$folder\"" >"$path/run.bat"
}

main
