#!/bin/sh

print_error() {
  printf "\033[0;31m%s\033[0m\n" "$1"
}

print_message() {
  printf "\033[0;32m%s\033[0m\n" "$1"
}

install_dependencies() {
  sudo apt update
  sudo apt install libsdl2-2.0-0 libsdl2-net-2.0-0 libopusfile0
}

get_source() {
  temp_path=/tmp/dosbox

  wget -P $temp_path https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.81.0/dosbox-staging-linux-v0.81.0.tar.xz
  tar -xvf $temp_path/dosbox-staging-linux-v0.81.0.tar.xz -C $temp_path

  sudo mv -f $temp_path/dosbox-staging-linux-v0.81.0 /opt/dosbox-staging

  rm -rf $temp_path
}

link_executeable() {
  sudo ln -s /opt/dosbox-staging/dosbox /usr/local/bin/dosbox
}

debian_check() {
  if apt >/dev/null 2>&1; then
    print_error "OS Family not supported."
    exit 1
  fi

}

install_dosbox() {
  if ! command -v dosbox >/dev/null; then
    print_message "Installing Dosbox."
    install_dependencies
    get_source
    link_executeable
  else
    print_message "Dosbox is already installed."
  fi
}

install_dn() {
  dn_path=dos/PROGS/DN

  if [ -f $dn_path/DN.COM ]; then
    print_message "Dos Navigator already installed."
    return
  fi

  print_message "Installing Dos Navigator."

  wget -P $dn_path https://www.ritlabs.com/download/dn/dn151.zip
  unzip $dn_path/dn151.zip -d $dn_path
  rm $dn_path/dn151.zip
}

link_config() {
  print_message "Linking Dosbox configuration."
  if [ ! -d ~/.config/dosbox ]; then
    mkdir ~/.config/dosbox
  fi

  ln -snf "$PWD"/dosbox/dosbox-staging.conf ~/.config/dosbox/dosbox-staging.conf
}

link_drive() {
  print_message "Linking dos folder to home."
  ln -snf "$PWD"/dos ~/dos
}

main() {
  debian_check
  install_dosbox
  install_dn
  link_config
  link_drive
  exit 0
}

main
