#!/bin/sh

drive=c

print_error() {
  printf "\033[0;31m%s\033[0m\n" "$1"
}

print_message() {
  printf "\033[0;32m%s\033[0m\n" "$1"
}

install_dependencies() {
  sudo apt update
  sudo apt install libsdl2-2.0-0 libsdl2-net-2.0-0 libopusfile0
}

get_source() {
  temp_path=/tmp/dosbox

  wget -P $temp_path https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.81.0/dosbox-staging-linux-v0.81.0.tar.xz
  tar -xvf $temp_path/dosbox-staging-linux-v0.81.0.tar.xz -C $temp_path

  sudo mv -f $temp_path/dosbox-staging-linux-v0.81.0 /opt/dosbox-staging

  rm -rf $temp_path
}

link_executeable() {
  sudo ln -s /opt/dosbox-staging/dosbox /usr/local/bin/dosbox
}

debian_check() {
  if apt >/dev/null 2>&1; then
    print_error "OS Family not supported."
    exit 1
  fi

}

install_dosbox() {
  if ! command -v dosbox >/dev/null; then
    print_message "Installing Dosbox."
    install_dependencies
    get_source
    link_executeable
  else
    print_message "Dosbox is already installed."
  fi
}

install_dos_program() {
  program_name=$1
  program_path=$drive/progs/$program_name
  program_exe=$2
  download_url=$3

  if [ -f "$program_path/$program_exe" ]; then
    print_message "$program_name already installed."
    return
  fi

  print_message "Installing $program_name."

  wget "$download_url" -O "$program_path/$program_name.zip"
  unzip "$program_path/$program_name.zip" -d "$program_path"
  rm "$program_path/$program_name.zip"
}

install_vim() {
    install_dos_program "vim" "vim/vim73/vim.exe" "https://ftp.nluug.nl/pub/vim/pc/vim73_46d32.zip"
    unzip -n $drive/progs/vim/vim/vim73/csdpmi4b.zip -d $drive/progs/vim/vim/vim73
}

install_dosfetch() {
    df_path=$drive/progs/df

    if [ -f "$df_path/df.exe" ]; then
      print_message "Dosfetch mini already installed."
      return
    fi

    print_message "Installing Dosfetch mini."

    wget https://github.com/leahneukirchen/dosfetch/raw/master/dosfetch.exe -O $df_path/df.exe
}

link_config() {
  print_message "Linking Dosbox configuration."
  if [ ! -d ~/.config/dosbox ]; then
    mkdir ~/.config/dosbox
  fi

  ln -snf "$PWD"/dosbox/dosbox-staging.conf ~/.config/dosbox/dosbox-staging.conf
}

link_drive() {
  print_message "Linking dos folder to home."
  mkdir ~/dos
  ln -snf "$PWD"/c ~/dos/c
}

main() {
  debian_check
  install_dosbox
  install_dos_program "dn" "DN.COM" "https://www.ritlabs.com/download/dn/dn151.zip"
  install_dos_program "edit" "EDIT.EXE" "https://archive.org/download/freedos_edit_09a_/EDIT.zip"
  install_vim
  install_dosfetch
  link_config
  link_drive
  exit 0
}

main
