---
- name: "Setup vim"
  tags: vim
  block:
    - name: "Check vim.exe"
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/dos/c/progs/vim/vim/vim73/vim.exe"
      register: vim_exe

    - name: "Download vim"
      ansible.builtin.get_url:
        url: "https://ftp.nluug.nl/pub/vim/pc/vim73_46d32.zip"
        dest: "/tmp"
      when: not vim_exe.stat.exists

    - name: "Unarchive vim"
      ansible.builtin.unarchive:
        src: "/tmp/vim73_46d32.zip"
        dest: "{{ ansible_env.HOME }}/dos/c/progs/vim"
      when: not vim_exe.stat.exists

    - name: "Unarchive csdpmi4b"
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/dos/c/progs/vim/vim/vim73/csdpmi4b.zip"
        dest: "{{ ansible_env.HOME }}/dos/c/progs/vim/vim/vim73"
      when: not vim_exe.stat.exists

    - name: "Check vim runtime files"
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/dos/c/progs/vim/vim/vim73/doc"
      register: vim_runtime

    - name: "Download vim runtime files"
      ansible.builtin.get_url:
        url: "https://ftp.nluug.nl/pub/vim/pc/vim73rt.zip"
        dest: "/tmp"
      when: not vim_runtime.stat.exists

    - name: "Unarchive vim runtime files"
      ansible.builtin.unarchive:
        src: "/tmp/vim73rt.zip"
        dest: "{{ ansible_env.HOME }}/dos/c/progs/vim"
      when: not vim_runtime.stat.exists
