---
- name: "Setup vim"
  tags: vim
  block:
    - name: "Check vim.exe"
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/dos/c/progs/vim/vim/vim73/vim.exe"
      register: vim_exe

    - name: "Download vim"
      ansible.builtin.get_url:
        url: "https://ftp.nluug.nl/pub/vim/pc/vim73_46d32.zip"
        dest: "/tmp"
      when: not vim_exe.stat.exists

    - name: "Unarchive vim"
      ansible.builtin.unarchive:
        src: "/tmp/vim73_46d32.zip"
        dest: "{{ ansible_env.HOME }}/dos/c/progs/vim"
      become: yes
      when: not vim_exe.stat.exists

    - name: "Unarchive csdpmi4b"
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/dos/c/progs/vim/vim/vim73/csdpmi4b.zip"
        dest: "{{ ansible_env.HOME }}/dos/c/progs/vim/vim/vim73"
      become: yes
